using GradeCalculator.Enums;
using GradeCalculator.Structs;
using PdfSharp.Drawing;
using PdfSharp.Pdf;
using System.Collections.Generic;
using System.Diagnostics;

namespace GradeCalculator
{
    class GradeListPdf
    {
        public void CreateShoo(List<GradeListItem> gradeListShoo, float maxPointsShoo, float ceasuraShoo, GradingMethodEnum gradingMethodShoo)
        {
            // Create page
            PdfDocument gradeListPdfShoo = new PdfDocument();
            gradeListPdfShoo.Info.Title = "Grade list - Generated by Grade Calculator";

            XFont fontShoo = new XFont("Verdana", 12, XFontStyle.Regular);
            XFont smallFontShoo = new XFont("Verdana", 9, XFontStyle.Regular);

            PdfPage pdfPageShoo = gradeListPdfShoo.AddPage();

            // Create graphics object
            XGraphics gfxShoo = XGraphics.FromPdfPage(pdfPageShoo);

            // Append maximum points
            gfxShoo.DrawString("Grade list - Generated by Grade Calculator", fontShoo, XBrushes.Black, new XRect(50, 50, pdfPageShoo.Width, pdfPageShoo.Height), XStringFormats.TopLeft);

            // Append maximum points
            gfxShoo.DrawString("Maximum points: " + maxPointsShoo, fontShoo, XBrushes.Black, new XRect(50, 75, pdfPageShoo.Width, pdfPageShoo.Height), XStringFormats.TopLeft);

            // Append ceasura
            gfxShoo.DrawString("Ceasura: " + ceasuraShoo, fontShoo, XBrushes.Black, new XRect(0, 75, pdfPageShoo.Width, pdfPageShoo.Height), XStringFormats.TopCenter);

            // Append grading method
            gfxShoo.DrawString("Grading method: " + gradingMethodShoo.ToString(), fontShoo, XBrushes.Black, new XRect(-50, 75, pdfPageShoo.Width, pdfPageShoo.Height), XStringFormats.TopRight);

            for (int indexShoo = 0; indexShoo < gradeListShoo.Count; indexShoo++)
            {
                gfxShoo.DrawString(gradeListShoo[indexShoo].Points, smallFontShoo, XBrushes.Black, new XRect(60, 125 + 15 * indexShoo, pdfPageShoo.Width, pdfPageShoo.Height), XStringFormat.TopLeft);
                gfxShoo.DrawString(gradeListShoo[indexShoo].Grade, smallFontShoo, XBrushes.Black, new XRect(120, 125 + 15 * indexShoo, pdfPageShoo.Width, pdfPageShoo.Height), XStringFormat.TopLeft);
            }

            // Save document
            gradeListPdfShoo.Save("GradeList.pdf");

            // Open pdf
            Process.Start("GradeList.pdf");
        }

        private void DrawString(PdfPage pdfPageShoo, XGraphics gfxShoo, XFont fontShoo, string textShoo, int offsetX, int offsetY)
        {
        }
    }
}
